# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be263c35934981b8f53d888995a1de23ab91aa07fb73b73a4e86fbd6d3e3ab7d9f1f5b9ea40c1c792112a9db70402e45b2cbd3f6041ca60c55f5cd0535f57de

test:
  secret_key_base: f8fb0a3b378e1dd6c60edd38621c08ab11098c9b1a332dceea0e7b932014fb5fe29297772536a1a7117db2fcfb228cde70386cb17a9f2a10ce1ffd6ea8c8d4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
